export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/signup',
  SIGNOUT = '/auth/signout',
  FORGOT_PASSWORD = '/auth/forgot-password',
  RESET_PASSWORD = '/auth/reset-password',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_USER = '/auth',
  FETCH_USERS = '/user',
  USERS_PREFIX = '/user',
  UPLOAD_AVATAR_IMAGE = '/user/upload',
  GET_AVATAR_IMAGE = '/user/get/image',
  LOCATION = '/location',
  UPLOAD_LOCATION_IMAGE = '/location/upload',
  GUESS = '/guess',
}
